export const jwtConst = {
  SECRET_KEY: 'HECHAOUWPxx.gssTT13944.JJHLLAPLWFMVxx1259XCVMN',
  ACCESS_TOKEN_EXPIRED_TIME: 3600,
  REFRESH_TOKEN_EXPIRED_TIME: 86400,
};
export enum EUserRole {
  User = 'USER',
  Admin = 'ADMIN',
}
